"use client"

import localFont from 'next/font/local'
import type {Metadata} from "next";
import {ThemeProvider} from "@mui/material/styles";
import {theme} from "@/components/theme";
import "./globals.css";
import {ProductProvider} from "@/components/contexts/ProductContext";

const peyda = localFont({
    src: './fonts/Peyda-Black.ttf',
    variable: '--font-peyda',
    display: 'swap',
})

let metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={`${peyda.variable}`}>
      <body>
      <ThemeProvider theme={theme}>
          <ProductProvider>
              {children}
          </ProductProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
